spring.application.name=transitops-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/transitops

spring.datasource.username=postgres
spring.datasource.password=sharan

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080